// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPurchase struct {
	Serie           string  `json:"serie"`
	Number          int     `json:"number"`
	ContactIdentity string  `json:"contact_identity"`
	ContactName     string  `json:"contact_name"`
	TotalPrice      float64 `json:"total_price"`
	TotalIgv        float64 `json:"total_igv"`
	IssueDate       string  `json:"issue_date"`
}

type NewUser struct {
	Name     string `json:"name"`
	Identity string `json:"identity"`
	UserID   string `json:"user_id"`
}
